config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :products 
  get 'home/index'
  get 'home/about'

  resources :categories
  root 'products#index'
  

end

app/models/bank_customer.rb
class BankCustomer < ActiveRecord::Base
	validates_presence_of :name, :acc_no, :balance
	validates_numericality_of :balance, greater_than_or_equal_to: 0
	validates_uniqueness_of :acc_no 

	def transaction(amount,code)
		if code == 0
			# if self.balance - amount < 0 
			# 	binding.pry
			# 	puts "Insufficient funds"
			# else
			# 	binding.pry
				self.balance = self.balance - amount
				self.update_attributes(balance: self.balance)
			# end
		else 
			self.balance += amount
			self.update_attributes(balance: self.balance)
		end
	end
end

app/models/cart_line_item.rb
class CartLineItem < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products

	validates_presence_of :name
	validates_uniqueness_of :name


end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :category 
	
	validates_presence_of :name, :price, :category_id, :description
	validates_numericality_of :price, :category_id, greater_than_or_equal_to: 1


	def details
		"#{self.name} - #{self.description} - #{self.price}"
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :mobile, :gender, :dob])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@categories = Category.all
  end

  def about 
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
=begin 
index 
	Role - is to list resources / data 
	path - products_path
	URI - /products
	HTTP Method - GET

new 
	Role - is to instantiate an object, and setup a form
	path - new_product_path
	URI - /products/new
	HTTP Method - GET

create
  Role - is to take the values coming in from the form and save it to the database if the validations pass, else display error message
  path - products_path
  URI - /products
  HTTP Method - POST 

show
	Role - is to find the data and display its details on the show page, along with it also to display is associated data
	path - product_path(:id)
	URI - /products/:id
	HTTP Mehtod - GET

edit
	Role - is to find the record from the db and display the details inside a form 
	Path - edit_product_path(:id)
	URI - /products/:id/edit
	HTTP Method - GET

update
  Role - is to find the record from the db the user is trying to update. and update the values of the record with the parameters coming in from the form if the validations pass, else display the error msg
  Path - product_path(:id)
  URI - /products/:id
  HTTP Method - PATCH

destroy 
	Role - is to find the record from the db and delete it, once deleted redirect the user to a new page. 
	Path - product_path(:id)
	URI - /products/:id
	HTTP Method - DELETE 
=end

def index
	@products = Product.all
end

def new
	@product = Product.new 
end

def create 
	@product = Product.new(params[:product].permit(:name, :category_id, :description, :price))
	if @product.save 
		redirect_to products_path, notice: "Successfully created product"
	else
		render action: "new"
	end
end

def show
	@product = Product.find(params[:id])
	# @category = Category.find(@product.category_id)
end

def edit
	@product = Product.find(params[:id])
end

def update
	@product = Product.find(params[:id])
	if @product.update_attributes(params[:product].permit(:name, :category_id, :description, :price))
		redirect_to product_path(@product.id), notice: "Successfully updated the product"
	else
		render action: "edit"
	end
end

def destroy
	@product = Product.find(params[:id])
	@product.destroy
	redirect_to products_path, notice: "Successfully destroyed the product"
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td>
          <%= category.name %> (<%= Product.where('category_id = ?', category.id).length %>)
        </td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<h2>Listing Products (<%= @category.products.length %>) </h2>
<ul>
	<!-- Product.where('category_id = ?',@category.id) -->
	<%  @category.products.each do |product| %>
		<li><%= link_to product.name, product_path(product.id) %> <%= product.price %></li>
	<% end %>
</ul>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/home/about.html.erb
<h2>About us</h2>

<a href="/home/index"> Home </a>

<%= link_to "Home (ror)", home_index_path %> 
<!-- home_index_path returns a string "/home/index" -->

app/views/home/index.html.erb
<h2>Welcome to our website</h2>
<!-- 
<%= %> is embedded ruby tag inside html used for presentation.

<% %> is embedded ruby tag inside html used for evaluation 
-->
2 + 2 : <%= 2 + 2 %> <!--  commenting in html -->
<% names = ["ramesh", "suresh", "veersh", "ganesh"] %>
<ul> <!-- unordered list -->
	<li>Virat</li>
	<li>Dhoni</li>
</ul>

<ol> <!-- ordered list -->
	<li>Apple</li>
	<li>Samsung</li>
	<li>Mi</li>
</ol>

<h3>Listing Names</h3>
<ol>
	<% names.each do |name| %>
		<li><%= name.capitalize %></li>
	<% end %>
</ol>

<% companies = [] %>
<% if companies.empty? %>
	<p> Companies not found </p>
<% else %>
	<h3>Listing Companies</h3>
	<ol>
		<% companies.each do |company| %>
			<li><%= company %></li>
		<% end %>
	</ol>
<% end %>

<a href="/home/about"> About</a>
<%= link_to "ABOUT (ror)", home_about_path %>
<!-- home_about_path returns a string "/home/about" -->

<h2>Listing Categories</h2>
<ol>
	<% @categories.each do |category| %>
		<li><%= category.name %></li>
	<% end %>
</ol>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ecommerce</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
	<%= current_user.username %>
	<%= link_to "Account Settings", edit_user_registration_path %> | 
	<%= link_to "Logout", destroy_user_session_path, method: :delete %>
<% else %>
	<%= link_to "Login", new_user_session_path %> | <%= link_to "Register", new_user_registration_path %> 
<% end %>

 <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/products/edit.html.erb
<h2>Edit Product</h2>

<%= form_for @product do |f| %>
	
	<% if @product.errors.any? %>
		<h3>These errors prohibitted the form from being saved : </h3>
		<ul>
			<% @product.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>


	<label>Name : </label><br/>
	<%= f.text_field :name, placeholder: "Enter product name", autofocus: true %>
	<span id="nameError"> </span>
	<br/>

	<label>Description : </label> <br/>
	<%= f.text_area :description %> <br/>

	<label>Price : </label><br/>
	<%= f.number_field :price, min: 1, step: 'any' %><br/>

	<label>Category : </label><br/>
	<%= f.collection_select :category_id, Category.all, :id, :name, prompt: "Select Category" %><br/>

	<%= f.submit %> or <%= link_to "back", products_path %>

<% end %> 
<script>
var nameHandle = document.getElementById('product_name');
var nameErrorHandle = document.getElementById('nameError');

nameHandle.onblur = function(){
	if(nameHandle.value == ""){
		nameErrorHandle.innerHTML = "Can't be blank";
	} else {
		nameErrorHandle.innerHTML = "";
	}
};
</script>

app/views/products/index.html.erb
<h2>Listing Products</h2>
<% if @products.empty? %>
		<p>No Products Found</p>
<% else %>
	<ul>
		<% @products.each do |product| %>
			<li><%= link_to product.name, product_path(product.id) %> - INR <%= product.price %>

				<%= link_to product.category.name, category_path(product.category_id) %>
				
				<%= link_to "show", product_path(product.id) %>
			</li>
		<% end %>
	</ul>
<% end %>

<%= link_to "Add Product", new_product_path %>
<!-- <a href="/products/new">Add Product</a> -->

app/views/products/new.html.erb
<h2>Add Product</h2>

<%= form_for @product do |f| %>
	
	<% if @product.errors.any? %>
		<h3>These errors prohibitted the form from being saved : </h3>
		<ul>
			<% @product.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>


	<label>Name : </label><br/>
	<%= f.text_field :name, placeholder: "Enter product name", autofocus: true %>
	<span id="nameError"> </span>
	<br/>

	<label>Description : </label> <br/>
	<%= f.text_area :description %> <br/>

	<label>Price : </label><br/>
	<%= f.number_field :price, min: 1, step: 'any' %><br/>

	<label>Category : </label><br/>
	<%= f.collection_select :category_id, Category.all, :id, :name, prompt: "Select Category" %><br/>

	<%= f.submit %> or <%= link_to "back", products_path %>

<% end %> 

<script>
var nameHandle = document.getElementById('product_name');
var nameErrorHandle = document.getElementById('nameError');

nameHandle.onblur = function(){
	if(nameHandle.value == ""){
		nameErrorHandle.innerHTML = "Can't be blank";
	} else {
		nameErrorHandle.innerHTML = "";
	}
};
</script>

app/views/products/show.html.erb
<h2><%= @product.name %></h2>
<p> PRICE : INR <%= @product.price %> </p>
<p> DETAILS:  <%= @product.description %> </p>
<p> CATEGORY : <%= link_to @product.category.name, category_path(@product.category_id) %> </p>

<%= link_to "List Products", products_path %>

<%= link_to "edit", edit_product_path(@product.id) %>

<%= link_to "destroy", product_path(@product.id), method: :delete, data: {confirm: "Are you sure?"} %>